### ISSUE TITLE
Publish `storage`

### ISSUE THREAD

**Issue by nxsaken** [Erigara/storage#2]
To publish `iroha`, we need to publish this crate also.

- [ ] Rename this crate, as `storage` is taken
- [ ] Change the dependency on `concread` to the published version

**Comment by Erigara** [comment]
Sure i will update to the latest `concread` version.
Any ideas about proper name? :)

**Comment by nxsaken** [comment]
How about `mv`? `mv::Cell`, `mv::Storage` look nice

**Comment by Erigara** [comment]
Published by name [`mv`](https://crates.io/crates/mv).
